//Link to get list of all todos
GET http://localhost:3000/todos/
###

//Link to get  todo By Id
GET http://localhost:3000/todos/2/
###

//Link to get todos whose status is TO DO
GET http://localhost:3000/todos/?status=TO%20DO
###

//Link to get todos whose priority is HIGH
GET http://localhost:3000/todos/?priority=HIGH
###

//Link to get todos whose priority is HIGH and status is IN PROGRESS
GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS
###

//Link to get todos whose todo contains "play" word
GET http://localhost:3000/todos/?search_q=Play
###

//Link to create a todo
POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}
###

//Link to udate specific details of todo
PUT http://localhost:3000/todos/1/
Content-Type: application/json

{
  "status": "DONE"
}
###

//Link to udate specific details of todo
PUT http://localhost:3000/todos/2/
Content-Type: application/json

{
  "priority": "HIGH"
}
###

//Link to udate specific details of todo
PUT http://localhost:3000/todos/4/
Content-Type: application/json

{
    "todo": "Some Task"
}
###

//Link to udate specific details of todo
DELETE http://localhost:3000/todos/10/
